# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interfaz.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(418, 335)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Nombre_Arch = QtWidgets.QLineEdit(self.centralwidget)
        self.Nombre_Arch.setGeometry(QtCore.QRect(80, 20, 113, 20))
        self.Nombre_Arch.setObjectName("Nombre_Arch")
        self.Texto_Escribir = QtWidgets.QLineEdit(self.centralwidget)
        self.Texto_Escribir.setGeometry(QtCore.QRect(80, 80, 113, 20))
        self.Texto_Escribir.setObjectName("Texto_Escribir")
        self.Num_Lin_Arch = QtWidgets.QLineEdit(self.centralwidget)
        self.Num_Lin_Arch.setGeometry(QtCore.QRect(80, 130, 113, 20))
        self.Num_Lin_Arch.setObjectName("Num_Lin_Arch")
        self.Num_Vocales = QtWidgets.QLineEdit(self.centralwidget)
        self.Num_Vocales.setGeometry(QtCore.QRect(50, 230, 113, 20))
        self.Num_Vocales.setObjectName("Num_Vocales")
        self.Num_Conson = QtWidgets.QLineEdit(self.centralwidget)
        self.Num_Conson.setGeometry(QtCore.QRect(250, 230, 113, 20))
        self.Num_Conson.setObjectName("Num_Conson")
        self.Boton = QtWidgets.QPushButton(self.centralwidget)
        self.Boton.setGeometry(QtCore.QRect(170, 170, 71, 21))
        self.Boton.setObjectName("Boton")
        self.Nombre_Arc_Label = QtWidgets.QLabel(self.centralwidget)
        self.Nombre_Arc_Label.setGeometry(QtCore.QRect(240, 20, 101, 16))
        self.Nombre_Arc_Label.setObjectName("Nombre_Arc_Label")
        self.Texto_Escr = QtWidgets.QLabel(self.centralwidget)
        self.Texto_Escr.setGeometry(QtCore.QRect(240, 80, 101, 16))
        self.Texto_Escr.setObjectName("Texto_Escr")
        self.Num_Lin_Label = QtWidgets.QLabel(self.centralwidget)
        self.Num_Lin_Label.setGeometry(QtCore.QRect(240, 130, 101, 16))
        self.Num_Lin_Label.setObjectName("Num_Lin_Label")
        self.Num_Voc_Label = QtWidgets.QLabel(self.centralwidget)
        self.Num_Voc_Label.setGeometry(QtCore.QRect(250, 200, 101, 16))
        self.Num_Voc_Label.setObjectName("Num_Voc_Label")
        self.Num_Cons_Label = QtWidgets.QLabel(self.centralwidget)
        self.Num_Cons_Label.setGeometry(QtCore.QRect(50, 200, 101, 16))
        self.Num_Cons_Label.setObjectName("Num_Cons_Label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 418, 18))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Boton.setText(_translate("MainWindow", "Analizar"))
        self.Nombre_Arc_Label.setText(_translate("MainWindow", "Nombre del Archivo"))
        self.Texto_Escr.setText(_translate("MainWindow", "Texto a escribir"))
        self.Num_Lin_Label.setText(_translate("MainWindow", "Número en líneas de archivo"))
        self.Num_Voc_Label.setText(_translate("MainWindow", "Número de vocales"))
        self.Num_Cons_Label.setText(_translate("MainWindow", "Número de consonantes"))
